// ============================================================
// SECURITY WARNING — DO NOT COMMIT REAL CREDENTIALS
//
// This file is AUTO-GENERATED by Figma Make with real values.
// It is listed in .gitignore and should NEVER be committed
// with actual project credentials.
//
// If you see real credentials in this file in git history,
// rotate them immediately in the Supabase dashboard:
//   Settings > API > Regenerate anon key
//
// For local development outside Figma Make:
//   1. Copy .env.example to .env.local
//   2. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY
//   3. The app will use env vars in production mode (config.ts)
// ============================================================

export const projectId = "YOUR_PROJECT_ID_HERE"
export const publicAnonKey = "YOUR_ANON_KEY_HERE"
