import type { PricingPlan, PlanAccessRule } from './types';
import { USE_MOCKS, API_BASE_URL, authHeaders, store, mockId, delay, now } from './api-core';

export async function getPlans(instId: string): Promise<PricingPlan[]> { if (USE_MOCKS) { await delay(); return store.plans.filter(p => p.institution_id === instId); } return (await (await fetch(`${API_BASE_URL}/institutions/${instId}/plans`, { headers: authHeaders() })).json()).data; }
export async function createPlan(instId: string, plan: Partial<PricingPlan>): Promise<PricingPlan> { if (USE_MOCKS) { await delay(); const n: PricingPlan = { id: mockId('plan'), institution_id: instId, name: plan.name || 'Novo Plano', description: plan.description, price: plan.price ?? 0, currency: plan.currency || 'BRL', is_default: plan.is_default ?? false, is_trial: plan.is_trial ?? false, trial_duration_days: plan.trial_duration_days, max_students: plan.max_students, features: plan.features || [], created_at: now(), updated_at: now() }; store.plans.push(n); return n; } return (await (await fetch(`${API_BASE_URL}/institutions/${instId}/plans`, { method: 'POST', headers: authHeaders(), body: JSON.stringify(plan) })).json()).data; }
export async function updatePlan(instId: string, planId: string, data: Partial<PricingPlan>): Promise<PricingPlan> { if (USE_MOCKS) { await delay(); const i = store.plans.findIndex(p => p.id === planId); if (i === -1) throw new Error(`Plan ${planId} not found`); store.plans[i] = { ...store.plans[i], ...data, updated_at: now() }; return store.plans[i]; } return (await (await fetch(`${API_BASE_URL}/institutions/${instId}/plans/${planId}`, { method: 'PUT', headers: authHeaders(), body: JSON.stringify(data) })).json()).data; }
export async function deletePlan(instId: string, planId: string): Promise<void> { if (USE_MOCKS) { await delay(); store.plans = store.plans.filter(p => p.id !== planId); return; } await fetch(`${API_BASE_URL}/institutions/${instId}/plans/${planId}`, { method: 'DELETE', headers: authHeaders() }); }
export async function getPlanRules(planId: string): Promise<PlanAccessRule[]> { if (USE_MOCKS) { await delay(); return store.planRules.filter(r => r.plan_id === planId); } return (await (await fetch(`${API_BASE_URL}/plans/${planId}/rules`, { headers: authHeaders() })).json()).data; }
export async function createPlanRule(planId: string, rule: Partial<PlanAccessRule>): Promise<PlanAccessRule> { if (USE_MOCKS) { await delay(); const n: PlanAccessRule = { id: mockId('rule'), plan_id: planId, resource_type: rule.resource_type || 'course', resource_id: rule.resource_id || '', permission: rule.permission || 'read', created_at: now() }; store.planRules.push(n); return n; } return (await (await fetch(`${API_BASE_URL}/plans/${planId}/rules`, { method: 'POST', headers: authHeaders(), body: JSON.stringify(rule) })).json()).data; }
