// ============================================================
// Axon — Environment Config (dual-mode: Figma Make + Production)
// ============================================================
//
// HOW IT WORKS:
//   - In FIGMA MAKE (DEV=true): ALWAYS uses auto-generated utils/supabase/info.tsx
//     Even if VITE_SUPABASE_* vars exist, they are IGNORED in dev mode to avoid
//     DNS conflicts between the sandbox and external Supabase projects.
//   - In PRODUCTION (DEV=false, i.e. Render/Vercel): reads from VITE_SUPABASE_* env vars.
//     Falls back to info.tsx values only if env vars are missing.
//
// RENDER/VERCEL ENV VARS:
//   VITE_SUPABASE_URL        https://xdnciktarvxyhkrokbng.supabase.co
//   VITE_SUPABASE_ANON_KEY   your permanent anon key
//   VITE_API_BASE_URL        (optional, usually NOT needed)
//                            Default: <VITE_SUPABASE_URL>/functions/v1/server
//                            ⚠️  Do NOT append /api — server routes are /server/...
// ============================================================

import { projectId as fmProjectId, publicAnonKey as fmAnonKey } from '/utils/supabase/info';

// ── URL normalization ────────────────────────────────────────
// Defensive fix for env vars missing protocol or having extra paths.
// Handles:
//   "//host.com"        → "https://host.com"
//   "host.com"          → "https://host.com"
//   "http://host.com"   → "https://host.com"
//   "https://host.com/" → "https://host.com"  (strips trailing slash)
function ensureHttps(url: string): string {
  let u = url.trim();
  if (u.startsWith('https://')) { /* ok */ }
  else if (u.startsWith('http://')) { u = u.replace('http://', 'https://'); }
  else if (u.startsWith('//')) { u = `https:${u}`; }
  else { u = `https://${u}`; }
  return u.replace(/\/+$/, ''); // strip trailing slashes
}

// ── Detect environment ──────────────────────────────────────
// import.meta.env.DEV === true in Figma Make preview (dev server)
// import.meta.env.DEV === false in production build (vite build)
const isDev = import.meta.env.DEV;

// FIX: .trim() prevents whitespace in env vars from causing DNS failures
const envUrl = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
const envKey = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim();
const envApiBase = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.trim();

// CRITICAL: In dev mode (Figma Make), ALWAYS use the auto-generated info.tsx.
// The VITE_* secrets may point to an external Supabase project that is
// unreachable from the sandbox (causes ERR_NAME_NOT_RESOLVED).
const isProduction = !isDev && !!(envUrl && envKey);

// ── Resolved values ─────────────────────────────────────────
// FIX: ensureHttps() handles env vars set without "https://" prefix
// (e.g. "//xdnciktarvxyhkrokbng.supabase.co" instead of "https://...")
export const supabaseUrl: string = isProduction
  ? ensureHttps(envUrl!)
  : `https://${fmProjectId}.supabase.co`;

export const supabaseAnonKey: string = isProduction
  ? envKey!
  : fmAnonKey;

// API base URL:
//   Production: VITE_API_BASE_URL or <SUPABASE_URL>/functions/v1/server
//   Figma Make: <auto-generated-url>/functions/v1/make-server-<id>
//
// ⚠️  The server routes are: /server/health, /server/auth/signin, etc.
//     Do NOT set VITE_API_BASE_URL to .../server/api — that will 404.
const FM_FUNCTION_NAME = 'make-server-ae4c3d80';
const PROD_FUNCTION_NAME = 'server';

export const apiBaseUrl: string = isProduction
  ? ensureHttps(envApiBase || `${supabaseUrl}/functions/v1/${PROD_FUNCTION_NAME}`)
  : `https://${fmProjectId}.supabase.co/functions/v1/${FM_FUNCTION_NAME}`;

// ── Expose environment for diagnostics ──────────────────────
export const environment = isProduction ? 'PRODUCTION' : 'FIGMA_MAKE';

// ── Debug: log config at startup ─────────────────────────────
console.log('[Config] Mode:', environment, `(DEV=${isDev})`);
console.log('[Config] Supabase URL:', supabaseUrl);
console.log('[Config] API Base URL:', apiBaseUrl);
if (isDev) {
  console.log('[Config] Anon Key:', supabaseAnonKey.substring(0, 20) + '...');
  if (envUrl) {
    console.log('[Config] Note: VITE_SUPABASE_URL is set but IGNORED in dev mode');
  }
}

// ── Sanity checks (production only) ─────────────────────────
if (isProduction) {
  if (envUrl && !envUrl.startsWith('https://')) {
    console.warn(
      `[Config] ⚠️  VITE_SUPABASE_URL was "${envUrl}" (missing https://). ` +
      `Auto-fixed to "${supabaseUrl}". Please correct the env var in Render/Vercel dashboard.`
    );
  }
  if (apiBaseUrl.endsWith('/api') || apiBaseUrl.endsWith('/api/')) {
    console.warn(
      `[Config] ⚠️  API Base URL ends with "/api" — this is likely WRONG. ` +
      `Server routes are /server/health, /server/auth/signin, etc. (no /api prefix). ` +
      `Delete VITE_API_BASE_URL from Render, or set it to: ${supabaseUrl}/functions/v1/server`
    );
  }
}
